### ISSUE TITLE
This plugin slows down homebridge

### ISSUE THREAD

**Issue by fate8383** [laundrify/homebridge-laundrify-official#3]
![image](https://user-images.githubusercontent.com/17381874/194134707-6cee6f1f-e465-430f-8d22-81d48b89c1ab.jpeg)

I am getting tons of these everyday, recently, it was ok but I feel like latest node update and whatever else plugin is not doing well. Great product and idea but without plugin it is kind of redundant. Could you please tell me where to look to fix this? Thanks

**Comment by mistertropi** [comment]
Same issue here! Need a fix

thanks!

**Comment by xLarry** [comment]
Thanks for reporting the issue.

There seems to be an infrastructural incident, starting from yesterday at around 7pm (UTC+2), which leads to a very high latency and packets being dropped.

We are currently investigating the issue and hope to fix it until end of day.

**Comment by fate8383** [comment]
could you please update here when resolved? currently i have plugin disabled. thanks

**Comment by xLarry** [comment]
The infrastructural incident has just been resolved. Some timeout errors might still occur in the next few hours until the DNS changes take full effect.

In case these errors still appear on your side, please let me know.

**Comment by fate8383** [comment]
Working fine now, thanks

**Comment by fate8383** [comment]
The same issue happening now, is it again infra?

**Comment by xLarry** [comment]
Could you please share some specific timestamps so I can cross-check the server logs and system metrics?

**Comment by fate8383** [comment]
[11/18/2022, 8:49:12 PM] [laundrify] E rror while polling Machine status:
ti
meout of 5000ms exceeded
[11/18/2022, 8:49:30 PM] [homebridge-1 aundrify-official] This plugin slows d own Homebridge. The read handler for t he characteristic 'Contact Sensor Stat e' was slow to respond! See https:/ /ho mebridge.io/w/JtMGR for more info.
[11/18/2022, 8:49:36 PM] [homebridge-1 aundrify-official] This plugin slows d own Homebridge. The read handler for t he characteristic 'Contact Sensor Stat e' didn't respond at all!. Please chec k that you properly call the callback!
See https://homebridge.io/w/JtMGR for more info.
[11/18/2022, 8:49:39 PM] [laundrify] E rror while loading Machine:
timeout o
£ 5000ms exceeded
[11/18/2022, 8:49:41 PM] [homebridge-1 aundrify-official] This plugin slows d own Homebridge. The read handler for t he characteristic
Contact Sensor Stat
e' was slow to respond! See https:/ /ho mebridge.io/w/JtMGR for more info.

**Comment by xLarry** [comment]
I couldn't find anything related in the logs or metrics.

However, the infra provider reported an increased latency and packet loss due to a DDoS attack on the given timestamp: https://www.netcup-status.de/2022/11/netzwerkstoerung-aufgrund-ddos-2/

According to the status page, the issue has been resolved at around 11pm. Could you please double-check if the errors occured again after that time?
