### ISSUE TITLE
No update for a long time is this product and plugin dead?

### ISSUE THREAD

**Issue by fate8383** [laundrify/homebridge-laundrify-official#4]
It has been really long time that I don't see any update on this plugin. Is the plugin not supported anymore?

Few things:
- why api is using port 80? It is simple to set some let's encrypt ssl and set to auto renew and be done with that.
- reverse on and off is still work as work around, when this will be an actual feature like promised in the past?
- I see the laundrify app of the device collects energy consumption information. Can we expose this to homebridge as well? So EVE app can show details of the energy consumption? I know home app does not but there are alternatives like EVE.
- continuous errors of this plugin slows down homebridge will be looked at?

Thanks

**Comment by xLarry** [comment]
It's open source; if you'd like to contribute, feel free to open a PR.

Bulk issues without any details or log files don't support our work in any way. Please create a proper issue for each problem you face with sufficient details to reproduce the problem.
