### ISSUE TITLE
Support for Homebridge 2.0

### ISSUE THREAD

**Issue by timwegenerDE** [laundrify/homebridge-laundrify-official#5]
Hi there,

I see the following message in the logs for this plugin:

NOTICE TO USERS AND PLUGIN DEVELOPERS
Homebridge 2.0 is on the way and brings some breaking changes to existing plugins.
Please visit the following link to learn more about the changes and how to prepare:
https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0

**Comment by xLarry** [comment]
Thanks for bringing this to my attention @timwegenerDE.

I just tested the plugin with Homebridge 2.0 and pushed a few minor changes to [v1.4.0](https://github.com/laundrify/homebridge-laundrify-official/releases/tag/v1.4.0) which should be ready for Homebridge v2.0 now.

Let me know if I missed anthing.
